### ISSUE TITLE
Can't transfer from NeonEVM Metamask wallet to Solana Neon address

### ISSUE THREAD

**Issue by ctapang** [neonlabsorg/neon-client-transfer#1]
I am trying to transfer my Neon tokens in NeonEVM to my Solana Neon address.
The default transfer is from Solana to NeonEVM, so the first step is to switch the direction of transfer (from Neon to Solana).
I then connect my Metamask NeonEVM wallet.
When I click the "Select a Token" dropdown, a list of tokens comes up, including NEON at the top. However, the NEON token is listed with the spinning wait icon and it remains spinning forever. I can't select it. I tried selecting every other token in the list, and it won't select.

**Comment by s-medvedev** [comment]
Do not reproduce on the last version.
