### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by Vevivo** [neonlabsorg/neon-client-transfer#11]
I'm sorry, but it's so boring and it's really tiring. After saying confirm, the wallet does the transaction, but there is still a confirmation screen on the screen, confusing people. No coins were swapped to wsol. It always gives slippage error. In the neon pass section, no coins are printed. please take care of it urgently.  0xa2aE6f0B2E8CC472c66905622ba244E58cB9813D

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
