### ISSUE TITLE
failed transactions

### ISSUE THREAD

**Issue by imbout2kms** [neonlabsorg/neon-client-transfer#12]
even though i have enough Neo and Sol on my wallets, somehow i cant use the bridge to complete the transfer, always a red notification pops and say
 [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32002,"message":"nonce too high: address 0x2eaebba4ba11f4f2c1ae1a2a8babb270d816e9a9, tx: 29 state: 28"}}}'

**Comment by s-medvedev** [comment]
Try to reset your account in MetaMask (Settings -> Advanced -> Reset Account).
