### ISSUE TITLE
neon to solana

### ISSUE THREAD

**Issue by dvl38** [neonlabsorg/neon-client-transfer#14]
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32002,"message":"nonce too high: address 0xc184869ba6bc29fa91748738b6ab7feead525ebf, tx: 43 state: 40"}}}'

**Comment by s-medvedev** [comment]
Try to reset your account in MetaMask (Settings -> Advanced -> Reset Account).
