### ISSUE TITLE
Transaction 

### ISSUE THREAD

**Issue by alexgki** [neonlabsorg/neon-client-transfer#19]
When performing transactions from Neon to Solana, where the source token is NEON, after transaction confirmation in Metamask, the transaction confirmation window does not pop up in Phantom as it does with USDC or USDT. In addition, the transaction freezes and the confirmation window that the transaction completed does not pop up, but the source token leaves Metamask and appears in Phantom.
![Neon Pass](https://user-images.githubusercontent.com/102022273/162188852-e9a16dba-09a6-4594-aeaf-bd3fb490b3dd.png)

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
