### ISSUE TITLE
transfer confirmation issue

### ISSUE THREAD

**Issue by karakushburak** [neonlabsorg/neon-client-transfer#20]
The transfer between networks takes place, but when the transfer is completed from solana, a confirmation message is received, but in the transfer from neon, no message is received even though the transfer is smooth.
![Uploading bggg.PNG…]()

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
