### ISSUE TITLE
Phantom Metamask Wait Problem

### ISSUE THREAD

**Issue by tolga25** [neonlabsorg/neon-client-transfer#21]
I wait 5-10 minute but no transfer.. 
![Ekran Alıntısı](https://user-images.githubusercontent.com/95562849/162281957-3fc83082-138a-4827-afba-139fc29ddb0e.JPG)

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.

**Comment by tolga25** [comment]
My wallet : 0x16d4011661E573fdCD58159c8d0736DEAABBD0d9

Thx team !
