### ISSUE TITLE
token balance and max sections

### ISSUE THREAD

**Issue by frkyc** [neonlabsorg/neon-client-transfer#23]
i think you must add "token balance" and "max" sections on your main page.
i know we can see the balance during token selection but the other sections will be more useful.
![issue 1](https://user-images.githubusercontent.com/85330886/162332254-70126041-7ce5-409b-85db-41147e67f22d.png)
![issue 2](https://user-images.githubusercontent.com/85330886/162332258-1af340ab-a301-478f-a948-868d0fe91e3f.png)
.

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
