### ISSUE TITLE
The request time is too long for more than 40 minutes. The task has been successfully completed within 10 seconds, but it has been stuck on the page.

### ISSUE THREAD

**Issue by walkerofcode** [neonlabsorg/neon-client-transfer#28]

**Comment by walkerofcode** [comment]
The request time is too long for more than 40 minutes. In fact, the task has been successful within 10 seconds, but it has been stuck in the page circle (from metamask to phantom), phantom to metamask is normal

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
