### ISSUE TITLE
Neon Pass

### ISSUE THREAD

**Issue by carasco11** [neonlabsorg/neon-client-transfer#29]
When I was tried Neon to Solana  it asked me SOL for transaction fee It needs to ask NEON for transaction so all my tarnsactions Failed on metamusk
![mora](https://user-images.githubusercontent.com/103234844/162358720-ec3ab78f-0e39-416f-b602-c92cab72dc57.png)
.

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/7.
