### ISSUE TITLE
CANNOT TRANSFER NEON FROM NEON CHAIN TO SOLANA

### ISSUE THREAD

**Issue by jiangweng1988** [neonlabsorg/neon-client-transfer#30]
I USE THE METAMASK WALLET(0xA5B2dEED6c977DF1ec32C90c948D17309cB03133) CANNOT TRANSFER NEON FROM NEON CHAIN TO SOLANA.  I  WAIT FOR 30 MINUTES  TO CONFIRM. BUT NO RESULTS

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
