### ISSUE TITLE
Neon pass slowly

### ISSUE THREAD

**Issue by Huypiaz** [neonlabsorg/neon-client-transfer#31]
The neon to solitary transfer has been pending for 1 hour in the following state. I tried it on both testnet and devnet networks in the phantom network. I also provided the faucet tokens for the fee. still does not perform the operation . Did anyone overcome the problem?

- [ ]

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
