### ISSUE TITLE
Neon Pass issue 

### ISSUE THREAD

**Issue by carasco11** [neonlabsorg/neon-client-transfer#32]
![swap](https://user-images.githubusercontent.com/103234844/162365442-32c10634-d476-44cb-896f-6996e0b2670b.png)

**Comment by carasco11** [comment]
several transactions were failed. always got this so cant transfer neon pass to Phantom wallet

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/7.
