### ISSUE TITLE
Operation Caton

### ISSUE THREAD

**Issue by 13551514** [neonlabsorg/neon-client-transfer#34]
![image](https://user-images.githubusercontent.com/102599920/162373386-658e0458-6523-4933-a708-f02ce1b02743.png)
The exchange has been completed, but the interface is always not updated, and the display transaction is still being processed

**Comment by 13551514** [comment]
my address：0xC35230c46C4B48B656eEFC9E6162b4dce959de5f

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
