### ISSUE TITLE
processing transaction

### ISSUE THREAD

**Issue by hattiepwvi** [neonlabsorg/neon-client-transfer#35]
The processing transaction can not stop, but money has been received by the wallet
![image](https://user-images.githubusercontent.com/103035354/162385770-354c9a5b-88f3-4b44-a9d1-b0362fc7b980.png)

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
