### ISSUE TITLE
page display problem

### ISSUE THREAD

**Issue by zgfwind** [neonlabsorg/neon-client-transfer#36]
The transaction was successful, but it kept going in circles.
![1011](https://user-images.githubusercontent.com/77773995/162393639-a0a861a5-ad33-4847-a342-e3ab1791d959.png)
![1010](https://user-images.githubusercontent.com/77773995/162393650-8206388d-5477-49bc-8ee5-2a5e919ccc90.png)

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
