### ISSUE TITLE
Sending error

### ISSUE THREAD

**Issue by fatih1225** [neonlabsorg/neon-client-transfer#39]
Processing a transaction takes too long and does not complete

**Comment by fatih1225** [comment]
[ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32002,"message":"nonce too high: address 0x2b6ed6808406701dfa0a37d194ac196a8a2944ae, tx: 21 state: 19"}}}'

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.

**Comment by s-medvedev** [comment]
Try to reset your account in MetaMask (Settings -> Advanced -> Reset Account).
