### ISSUE TITLE
işlem görünmüyor

### ISSUE THREAD

**Issue by ozk07** [neonlabsorg/neon-client-transfer#41]
NEON PASS seems to be in progress. But the Phantom wallet also seems to have the NEON token.
  

![NEON](https://user-images.githubusercontent.com/100947096/162455017-d52c9be4-bca0-4c95-bc87-adeeb6a6c1dc.png)

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
