### ISSUE TITLE
the transaction with no response

### ISSUE THREAD

**Issue by xu405049495** [neonlabsorg/neon-client-transfer#42]
my test  address is  0xd5985b3a8A0F18EDd20E92c15D72F3785f6aCCD4 . i do the test in the final steps . i get the neon  from and sol to.  i transform 100 and  click next .the transaction is waiting and no response

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
