### ISSUE TITLE
issues new

### ISSUE THREAD

**Issue by vantoanpaya** [neonlabsorg/neon-client-transfer#46]
Hello project team. i'm a testnet version of neon swap. i have a problem can't do the token swap from Neon to Solana it's been 10 minutes but the transaction has not been confirmed. my transaction address is 0x6Ca3638455c4eFFEF791f55eFf2076273957AdE8 solana address HbrF98ySL8PQTrfzr9oUkjHjkrqUp45see9o3pzCtGMY

**Comment by WebKieth** [comment]
Related to:
https://github.com/neonlabsorg/neon-support/issues/6
Fix was deployed
