### ISSUE TITLE
transfer metamask to phantom

### ISSUE THREAD

**Issue by arnon0208** [neonlabsorg/neon-client-transfer#51]
![1 hours](https://user-images.githubusercontent.com/41884054/162575961-539ca6a4-729e-459f-bd4d-98284571faf4.jpg)

im waiting one hours not confirm and success maybe history transaction shows in neon pass

**Comment by yunanni** [comment]
You will need to synchronize your wallet and then you debug it with bech13

**Comment by FrankDev34** [comment]
Talk to a Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.
