### ISSUE TITLE
Unusual Transaction Time

### ISSUE THREAD

**Issue by miorightone** [neonlabsorg/neon-client-transfer#61]
<img width="843" alt="unusual transaction time" src="https://user-images.githubusercontent.com/101451449/162624025-ab9f6a17-0202-45ff-868e-637f0f2bae2d.png">

Hello There. 
Here is the problem. When I testing Transfer Tokens function on testnet.(check: https://neonswap.live/#/pool) that the transaction time was unusually longer than what it supposed to be (last try was within 20 seconds) which takes more than 5mins to transfer. I have to stop processing to continue test since by clicking "Reject Processing" with no response. 

Actually, transactions did completed when I try to transfer reversely, which means tokens transferred to aimed wallet successfully even the UI displayed in process or processing stopped. 

It might be a bug, which need to be fixed up.
If confused by what I said, please refer to attached screenshot. Thank you.

Mio
Testing Wallet: 
0x556e77A899306A640F656Fcc93fA6bbf8FCf0cC9

Email: l
ynn.lindan@gmail.com
<img width="1154" alt="complete" src="https://user-images.githubusercontent.com/101451449/162624761-08c6e14c-8800-4839-807e-1a6d165701e0.png">

**Comment by WebKieth** [comment]
Related to:
https://github.com/neonlabsorg/neon-support/issues/6
Fix was deployed
