### ISSUE TITLE
交易问题

### ISSUE THREAD

**Issue by luluzero** [neonlabsorg/neon-client-transfer#7]
交易已经完成，从小狐狸到幻影钱包跨链，幻影钱包已经收到了币，但是页面一直显示处理中。
![image](https://user-images.githubusercontent.com/49665875/161965369-e308f274-9f86-4c7d-b0cb-a46824f3bd40.png)
![image](https://user-images.githubusercontent.com/49665875/161965441-11b107d7-9ad8-4de8-90e6-b5278f6cbc08.png)

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
