### ISSUE TITLE
neon to sol bug

### ISSUE THREAD

**Issue by luluzero** [neonlabsorg/neon-client-transfer#8]
Transferring coin knife sol chain from neon network, the page shows that it has been in progress, but the coins have already arrived at sol, which is a bug.
My email is xjqlfy@gmail.com I can help to reproduce it.

**Comment by s-medvedev** [comment]
Thank you for your interest in the project. We are working on this issue now. You can see its progress at https://github.com/neonlabsorg/neon-support/issues/6.
