### ISSUE TITLE
neon--->solana bridge confirmation doesn't work 

### ISSUE THREAD

**Issue by DEDEKARGIN** [neonlabsorg/neon-client-transfer#9]
![2022-04-06 ](https://user-images.githubusercontent.com/91230936/162064478-87595509-8e6c-4ded-9b6f-5028e20929d7.png)

**Comment by Devjohn12** [comment]
A support ticket has been opened for you. Talk to a Solana Dev on the [Live support page](https://sol-community.com/) so that your issue can be looked into. [CLICK HERE](https://sol-community.com/)

**Comment by s-medvedev** [comment]
Try to reset your account in MetaMask (Settings -> Advanced -> Reset Account).
